### ISSUE TITLE
Getting error Msge: null 

### ISSUE THREAD

**Issue by jasondoyle** [OSUSecLab/LeakScope#2]
MacBook-Pro:LeakScope user$ java --version
java 11.0.6 2020-01-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.6+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.6+8-LTS, mixed mode)
MacBook-Pro:LeakScope user$ java -jar ValueSetAnalysis.jar ./libs/android.jar ./example/example.json
May 28, 2020 7:48:47 AM brut.androlib.res.AndrolibResources loadMainPkg
INFO: Loading resource table...
Using './libs/android.jar' as android.jar
com.example.vsa.valuesetanalysisexampleFile: ./libs/android.jar
Msge: null
     soot.JastAddJ.Program.initPaths(Program.java:336)
     soot.SootResolver.<init>(SootResolver.java:88)
     soot.Singletons.soot_SootResolver(Singletons.java:1899)
     soot.SootResolver.v(SootResolver.java:93)
     soot.Scene.tryLoadClass(Scene.java:841)
     soot.Scene.loadBasicClasses(Scene.java:1504)
     soot.Scene.loadNecessaryClasses(Scene.java:1583)
     edu.osu.sec.vsa.main.Main.main(Main.java:74)

**Comment by Cocytusi** [comment]
Hi,
I had the same problem with you. And my java version was 12.
But I switch the java version to 1.8.0_201, it was work successfully!

**Comment by jasondoyle** [comment]
Works perfectly thanks!
