### ISSUE TITLE
When running this program, I'm having a problem, how do I solve this problem?

### ISSUE THREAD

**Issue by yangdazhuo816** [OSUSecLab/LeakScope#3]
![image](https://user-images.githubusercontent.com/56714714/97992176-4c6c8f80-1e1d-11eb-94bc-4b415e946bb5.png)

**Comment by yangdazhuo816** [comment]
Msge: null
     soot.JastAddJ.Program.initPaths(Program.java:336)
     soot.SootResolver.<init>(SootResolver.java:88)
     soot.Singletons.soot_SootResolver(Singletons.java:1899)
     soot.SootResolver.v(SootResolver.java:93)
     soot.Scene.tryLoadClass(Scene.java:841)
     soot.Scene.loadBasicClasses(Scene.java:1504)
     soot.Scene.loadNecessaryClasses(Scene.java:1583)
     edu.osu.sec.vsa.main.Main.main(Main.java:74)

**Comment by cszuo** [comment]
Please provide more information about the error
